AWSTemplateFormatVersion: "2010-09-09"
Description: ALB + TargetGroup + LaunchTemplate + ASG (nginx) + EFS mount

Parameters:
  AmiId:
    Type: String
    Description: "AMI to use for WordPress nodes (your new golden AMI)"
    Default: ami-03ebbd71503bf5fed   # <-- byt till ditt nya AMI-ID
  EfsId:
    Type: String
    Description: "EFS FileSystem ID (ex: fs-xxxxxxxxxxx)"
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: "VPC to use"
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "At least two subnets in different AZs"
  AlbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Existing SG for ALB"
  WebSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Existing SG for web/ASG"
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues: [ t3.micro, t3.small, t3.medium ]
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  

Resources:
  EC2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPath: /wordpress/
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 3

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Type: application
      Subnets: !Ref Subnets
      SecurityGroups: [ !Ref AlbSecurityGroupId ]

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref EC2TargetGroup

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-lt
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref WebSecurityGroupId
      

  WebServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref Subnets
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: "3"
      DesiredCapacity: "3"
      MaxSize: "3"
      TargetGroupARNs: [ !Ref EC2TargetGroup ]
      HealthCheckType: ELB
      HealthCheckGracePeriod: 180
      

      Tags:
        - Key: Name
          Value: wp-web-node
          PropagateAtLaunch: true

Outputs:
  AlbDNS:
    Description: "ALB DNS name"
    Value: !GetAtt ApplicationLoadBalancer.DNSName
